version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: light_it_challenge
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - mynetwork

  backend:
    build: 
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
