version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: light_it_challenge
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  backend:
    build: 
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  frontend:
    build: 
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
        - mynetwork

networks:
  mynetwork:
    driver: bridge
